fixtures:
  repositories:
    stdlib: 
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "3.2.0"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.1.1"
    # transitive requirement of augeasproviders_shellvar
    augeasproviders_core:
      repo: "git://github.com/hercules-team/augeasproviders_core.git"
    augeasproviders_shellvar:
      repo: "git://github.com/hercules-team/augeasproviders_shellvar.git"
  symlinks:
    "nfs": "#{source_dir}"
