fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "concat": "git://github.com/puppetlabs/puppetlabs-concat.git"
    "augeasproviders": "git://github.com/hercules-team/augeasproviders.git"
  symlinks:
    "nfs": "#{source_dir}"
